services:
  mysql:
    container_name: quizz-app-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_master
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - quizz-app-network
    #    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mail-dev:
    container_name: quizz-app-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - quizz-app-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: quizz-app-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quiz_db
      SPRING_DATASOURCE_USERNAME: quiz_master
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "10000:10000"
    networks:
      - quizz-app-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: quizz-app-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - quizz-app-network

networks:
  quizz-app-network:
    name: quizz-app-network

volumes:
  mysql-data:
    name: quizz-app-mysql-data
