services:
  mysql:
    container_name: mysql-quizz
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_master
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - quizz-network
#    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mail-dev:
    container_name: mail-dev-quizz
    image: maildev/maildev
    ports:
    - "1080:1080"
    - "1025:1025"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pcbuilder-backend
    ports:
      - "10001:10001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PCBuilderBackend?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - quizz-network

networks:
  quizz-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
