server:
  port: 10000
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    name: Quizzus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: quiz_master
    password: password
    url: jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1021798723236-ruvtmh631s5pq1lgn9ivuud9mqicpuch.apps.googleusercontent.com
            client-secret: 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
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: b71e28507d6c0c573d4c47d50b9e97e287dff22ce6ca52d042fc645836fd6aba627187dc75517c75c0c084c66b5670306844f78125261a00b1b3d7ad38dd84540f2512648e008de02319ab0a3c330a5b704607f4ab0cd33908eb13ec94f5c3268c03deaf5c1c74980cb0b25629c25951c01ca73e86845f4d20b86e7d1909efdfa1a331fbd0a9bd4f3389e79bc67849282236ad01f3b07fa38e647c6c3476b6ea2d08252dfc77e03954ef1ac365b042fb3b7b4c8e9e49d8677156a41b6c69cd22f28e62182d4bd166d1700028b992c108f7bbd5fc35c38fcd64b4c807e0c57a305f3fe4b14034c1b04347869aa20d19dffa166e47842729e75207821374a83cb8
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account