server:
  port: 10000
spring:
  graphql:
    graphiql:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: "${email}"
    password: "#{email-password}"
    properties:
      mail:
        smtp:
          trust: "smtp.gmail.com"
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    name: Quizzus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: quiz_master
    password: password
    url: jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${google-client-id}"
            client-secret: "${google-secret}"
            scope:
              - email
              - profile
            redirect-uri: http://localhost:10000/login/oauth2/code/google
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: "${secret-key}"
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account
